.TH GNMSGID 1 "gnmsgid" "17 March 2003" "Husky - Portable Fidonet Software"
.SH NAME
gnmsgid \- standalone msgid generator
.SH SYNOPSIS
.B gnmsgid
[-h] [-v] [-seqdir <path>] [-seqoutrun <outrun>] [<num>]
.SH "DESCRIPTION"
.B gnmsgid
print new msgid to stdout.
.br
.SH OPTIONS
.B [-h]
print usage information and exit
.br
.B [-v]
print version and exit
.br
.B [-seqdir <path>]
specify msgid sequencer directory (see husky docs)
.br
.B [-seqoutrun <outrun>]
specify msgid outrun value (see husky docs)
.br
.B [<num>]
number msgid to generate
.br
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at 
http://husky.sourceforge.net/team.html.
.SH AUTHOR
This manual page was written by Pavel Andreew <pavel@collage.etel.ru>
