os: linux
dist: bionic
language: c

jobs:
  include:
    - os: linux
      language: c
      env:
        - CF=-DBUILD_SHARED_LIBS=OFF
    - os: linux
      language: c
      env:
        - CF=-DBUILD_SHARED_LIBS=ON

before_install:
  - sudo apt-get install -y rpm
  - wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
  - sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
  - sudo apt-get update; sudo apt-get install -y pvs-studio

before_build:
  - huskylib_mdate=$(git log -1 --date=short --format=format:"%cd" huskylib/*.h src/*.c); echo "char cvs_date[]=\"$huskylib_mdate\";" > cvsdate.h; ls -l; cat ./cvsdate.h

script:
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH
  - echo TRAVIS_TAG=$TRAVIS_TAG
  - eval "${MATRIX_EVAL}"
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer credentials -o $TRAVIS_BUILD_DIR/PVS-Studio.lic $PVS_USERNAME $PVS_KEY; fi
  - if [[ -n "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
  - if [[ -z "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer trace -- cmake --build build; else cmake --build build; fi
  - if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer analyze -l $TRAVIS_BUILD_DIR/PVS-Studio.lic -s $TRAVIS_BUILD_DIR/suppress_base.json -o build/pvs.log; fi
  - if [[ -n "$PVS_USERNAME" ]]; then plog-converter -a 'GA:1,2;64:1,2;OP:1,2' -t tasklist -o build/pvs.tasks build/pvs.log; fi
  - if [[ -n "$PVS_USERNAME" ]]; then cat build/pvs.tasks; fi
  - if [[ -n "$PVS_USERNAME" ]]; then ! grep -vP '\serr\s+Help:' build/pvs.tasks | grep -P '\serr\s'; fi
  - cd build
  - cpack
