# $Id$
# Microsoft Visual C++ Makefile for build static library

CC=     cl
CFLAGS= -nologo -Zp1 -I..\h
CDEFS=  -D__NT__ -D_CONSOLE -DPROCESSOR_ARCHITECTURE="$(PROCESSOR_ARCHITECTURE)"
COPT=   -O2
TLIB=    lib -nologo
OBJ=	.obj

include makefile.inc

TARGETLIB = $(LIBNAME)mvc.lib

{$(SRC_DIR)}.c$(OBJ):
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<

all: $(TARGETLIB)

$(TARGETLIB): $(OBJS)
	$(TLIB) /out:$@ $(OBJS)


clean:
	-del *$(OBJ)

distclean: clean
	-del $(TARGETLIB)
