# Makefile for building a Windows 95 / NT HUSKY library
# with Borland C++ 4.0 for Win32
# No support for the Husky build environment

# Predefined macro: __WIN32__ , __TURBOC__

CC=     BCC32
CFLAGS= -WC
CDEFS=
COPT=
LIB=    tlib
OBJ=	.obj

TARGET= huskybcw.lib

include makefile.inc

# Thunderbirds are go!

.c.obj:
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) -c $<
	$(LIB) $(TARGET) -+$@

$(TARGET): $(OBJS)

clean:
	-DEL *.obj

distclean: clean
	-DEL $(TARGET)
